# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    needs: build
    concurrency:
      group: first-group
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with flake8
      run: poetry run task lint

  formatter:
    needs: build
    concurrency:
      group: second-group
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snok/install-poetry@v1.3.4
    - name: Format code
      run: poetry run task formatter

  security:
    needs: build
    concurrency:
      group: third-group
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snok/install-poetry@v1.3.4
    - name: Security checks
      run: poetry run task security
      
  unittests:
    needs: [lint, formatter, security]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snok/install-poetry@v1.3.4
    - name: Unit tests
      run: poetry run task test

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - uses: snok/install-poetry@v1.3.4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        poetry install
